var jsonObjChart = {  
   "base":{  
      "depth":"3",
      "bgColor":"FFF,333",
      "bgAngle":"-125",
      "showValues":"0",
      "chartTopMargin":"10",
      "chartRightMargin":"8",
      "chartBottomMargin":"0",
      "chartLeftMargin":"10"
   },
   "bars":{  
      "isColumn":"0",
      "barsGradientOpacity":"30",
      "barsHoverColor":"CCC",
      "barsSpacing":"15",
      "barsGradientAngle":"90",
      "barsMaxHeightCoef":"0.13"
   },
   "canvas":{  
      "canvasPadding":"10",
      "canvasBgColor":"e6e6e6,ffffff",
      "canvasBgAlpha":"100",
      "canvasBgAngle":"225",
      "outCnvBaseFont":"SegoeUI,Tahoma,Verdana",
      "outCnvBaseFontSize":"13"
   },
   "divlines":{  
      "numDivLines":"19",
      "showAlternateHGridColor":"1",
      "AlternateHGridAlpha":"100",
      "AlternateHGridColor":"CCCCCC"
      },
   "headings":{  
      "rotateCategoryNames":"1"
   },
   "legend":{  
      "showLegend":"0"
   },
   "scales":{  
      "yAxisMaxValue":"100"
   },
   "categories":{  
      "category":[ 
      ]
   },
   "data":[  
      {  
         "color":"AFD8F8",
         "set":[
         ]
      }
   ]
}